steps:
  # 1단계: 도커 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vertex-ai-api:$SHORT_SHA'
      - '.'
  # 2단계: 도커 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vertex-ai-api:$SHORT_SHA'
  # 3단계: Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vertex-ai-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vertex-ai-api:$SHORT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/vertex-ai-api:$SHORT_SHA'

